### ISSUE TITLE
feat(scss): Add styles [wip]

### ISSUE THREAD

**Issue by BorisDutkin** [BorisDutkin/svvs#12]
## Tasks List

- [x] add general styles

`npm install @angular/material @angular/cdk @angular/flex-layout @angular/animations`

`npm install bootstrap@next`

`ng add @ng-bootstrap/ng-bootstrap`

- [x] add generic styles
- [x] add style frameworks

*Links*
[Angular | Material](https://material.angular.io)
[Bootstrap | Material](https://getbootstrap.com/docs/4.0/getting-started/theming/)
