### ISSUE TITLE
feat(api-auth): add authentication[wip]

### ISSUE THREAD

**Issue by BorisDutkin** [BorisDutkin/svvs#14]
## Tasks List

- [x] add password packages

`npm i graphql-type-json`
`npm i --save @nestjs/passport passport @nestjs/jwt passport-jwt bcrypt`
`npm i --save-dev @types/passport-jwt`

- [x] add global interfaces
- [x] create Users module
- [ ] create Auth module
- [ ] create a migration
- [ ] write tests
