### ISSUE TITLE
feat(admin app * nx workspace): add admin app [wip]

### ISSUE THREAD

**Issue by BorisDutkin** [BorisDutkin/svvs#2]
## Tasks List

- [x] add admin app  
`nx generate @nrwl/angular:application frontend/admin --style=scss`
- [x] add different ports for client/admin projects
- [x] add tags
[Nx | Use Tags](https://nx.dev/latest/angular/structure/monorepo-tags)
- [x] linters, prettier configuration
