### ISSUE TITLE
feat(db): add postgresql db [wip]

### ISSUE THREAD

**Issue by BorisDutkin** [BorisDutkin/svvs#8]
## Tasks List

- [ ] install postgresql dependencies
`npm install --save @nestjs/typeorm typeorm pg`
- [ ] import typeorm module to the app.module.ts
- [ ] .env file setup
- [ ] create database
